### ISSUE TITLE
Large CPU and Battery Life Usage

### ISSUE THREAD

**Issue by rayliverified** [CppShane/GradientBackgroundAnimation-Repository#1]
The effect is great but there is a noticeable CPU usage of 5-12% when running on my Sony Xperia Performance X test device with a Qualcomm Snapdragon 820. 
Is there any way to lower the CPU usage? I have tried reducing the size of the ImageView and the dimensions of the gradient files but they have seemingly no effect on CPU usage. 
Any thoughts?

**Comment by cppshane** [comment]
Sadly, animations are just really CPU intensive. This method is more of a workaround than anything, and the most efficient way would be to algorithmically define a background gradient and redraw each pixel as per desired. I don't doubt that this would be significantly faster performance wise, however it would take much more time to create.

**Comment by rayliverified** [comment]
Hopefully, some kind soul will one day release an OpenGL gradient that performs great. Why is it so hard for Google to figure out gradients so us Android developers can actually create all the beautiful UI mockups on materialup.com and compete with iOS. :P
